d <- read.csv("data/processed/participants_scored.csv")
cat("iri_fs range:", min(d$iri_fs, na.rm=TRUE), max(d$iri_fs, na.rm=TRUE), "\n")
cat("iri_ec range:", min(d$iri_ec, na.rm=TRUE), max(d$iri_ec, na.rm=TRUE), "\n")
cat("iri_pt range:", min(d$iri_pt, na.rm=TRUE), max(d$iri_pt, na.rm=TRUE), "\n")
cat("iri_pd range:", min(d$iri_pd, na.rm=TRUE), max(d$iri_pd, na.rm=TRUE), "\n")
cat("means:", mean(d$iri_fs, na.rm=TRUE), mean(d$iri_ec, na.rm=TRUE), mean(d$iri_pt, na.rm=TRUE), mean(d$iri_pd, na.rm=TRUE), "\n")
d_j <- read.csv("data/processed/judgments_analysis.csv")
cat("group_target levels:", paste(sort(unique(d_j$group_target)), collapse=", "), "\n")
cat("group_other levels:", paste(sort(unique(d_j$group_other)), collapse=", "), "\n")
cat("obs_group levels:", paste(sort(unique(d_j$obs_group)), collapse=", "), "\n")
cat("role levels:", paste(sort(unique(d_j$role)), collapse=", "), "\n")
